"""Project Noralet simulation package."""

from importlib import import_module

from noralet.simulation import (
    ActionIntent,
    ActiveSignal,
    ConsumableEnergyPoint,
    DeterministicRandomStreams,
    EnergyConservationError,
    EnergyConsumed,
    EnergyEcologyConfig,
    EnergyPointDecayed,
    EnergyPointDissolved,
    EnergyPointFormed,
    EnergyTotals,
    EnvironmentalEnergyPool,
    ExternalPercept,
    FormationProbabilities,
    Interoception,
    NoraletActuatorConfig,
    NoraletAccelerated,
    NoraletBodyState,
    NoraletDeathCause,
    NoraletDied,
    NoraletEnergyConfig,
    NoraletPhysiologyConfig,
    NoraletEnergyExpenditureReason,
    NoraletEnergyReleased,
    NoraletEnergySpent,
    NoraletExperience,
    NoraletExperienceConfig,
    NoraletMoved,
    NoraletSignalConfig,
    SensorimotorFeedback,
    SignalDirection,
    SignalEmissionIntent,
    SignalEmitted,
    SignalPercept,
    SignalType,
    RegionDefinition,
    RegionKind,
    RoutedNoraletExperience,
    Simulation,
    SimulationConfig,
    SimulationEvent,
    TickAdvanced,
    TickResult,
    WorldState,
    condition_after_tick,
    mortality_hazard,
    natural_death_probability,
)

_BRAIN_EXPORTS = frozenset(
    (
        "ACTION_RANDOM_DRAW_ORDER",
        "ACTION_VECTOR_SIZE",
        "ActionEligibilityTraces",
        "AutonomousSimulationRunner",
        "AutonomousTickResult",
        "BaseBrain",
        "BASE_BRAIN_INITIALIZATION_VERSION",
        "BaseBrainInitializationConfig",
        "BrainActionSelection",
        "BrainActionParameters",
        "ExperienceEncoder",
        "HomeostaticPlasticityResult",
        "NoraletBrain",
        "NoraletBrainConfig",
        "NoraletBrainModel",
        "NoraletHomeostaticLearningResult",
        "NoraletHomeostaticPlasticityConfig",
        "NoraletLearningConfig",
        "NoraletLearningResult",
        "PredictionModel",
        "PredictiveLearningResult",
        "SignalMotorChoice",
        "homeostatic_drive",
        "homeostatic_modulation",
        "base_brain_initialization_manifest",
        "resolve_brain_device",
    )
)


def __getattr__(name: str) -> object:
    """Load the optional heavy neural API only when it is requested."""

    if name not in _BRAIN_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module("noralet.brain"), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set((*globals(), *_BRAIN_EXPORTS)))

__all__ = [
    "ACTION_RANDOM_DRAW_ORDER",
    "ACTION_VECTOR_SIZE",
    "ActionEligibilityTraces",
    "ActionIntent",
    "ActiveSignal",
    "AutonomousSimulationRunner",
    "AutonomousTickResult",
    "BaseBrain",
    "BASE_BRAIN_INITIALIZATION_VERSION",
    "BaseBrainInitializationConfig",
    "BrainActionSelection",
    "BrainActionParameters",
    "ConsumableEnergyPoint",
    "DeterministicRandomStreams",
    "EnergyConservationError",
    "EnergyConsumed",
    "EnergyEcologyConfig",
    "EnergyPointDecayed",
    "EnergyPointDissolved",
    "EnergyPointFormed",
    "EnergyTotals",
    "EnvironmentalEnergyPool",
    "ExternalPercept",
    "ExperienceEncoder",
    "FormationProbabilities",
    "HomeostaticPlasticityResult",
    "Interoception",
    "NoraletActuatorConfig",
    "NoraletAccelerated",
    "NoraletBodyState",
    "NoraletBrain",
    "NoraletBrainConfig",
    "NoraletBrainModel",
    "NoraletHomeostaticLearningResult",
    "NoraletHomeostaticPlasticityConfig",
    "NoraletLearningConfig",
    "NoraletLearningResult",
    "NoraletDeathCause",
    "NoraletDied",
    "NoraletEnergyConfig",
    "NoraletEnergyExpenditureReason",
    "NoraletEnergyReleased",
    "NoraletEnergySpent",
    "NoraletExperience",
    "NoraletExperienceConfig",
    "NoraletMoved",
    "NoraletPhysiologyConfig",
    "NoraletSignalConfig",
    "PredictionModel",
    "PredictiveLearningResult",
    "RegionDefinition",
    "RegionKind",
    "RoutedNoraletExperience",
    "Simulation",
    "SimulationConfig",
    "SimulationEvent",
    "SensorimotorFeedback",
    "SignalDirection",
    "SignalEmissionIntent",
    "SignalEmitted",
    "SignalMotorChoice",
    "SignalPercept",
    "SignalType",
    "TickAdvanced",
    "TickResult",
    "WorldState",
    "condition_after_tick",
    "homeostatic_drive",
    "homeostatic_modulation",
    "base_brain_initialization_manifest",
    "mortality_hazard",
    "natural_death_probability",
    "resolve_brain_device",
]
